<?xml version="1.0"?>

<robot 
    xmlns:xacro="http://www.ros.org/wiki/xacro"
    xmlns:sensor="htttp:/playerstage.sourceforce.net/gazebo/xmlschema/#sensor"
    xmlns:controller="htttp:/playerstage.sourceforce.net/gazebo/xmlschema/#controller"
    xmlns:interface="htttp:/playerstage.sourceforce.net/gazebo/xmlschema/#interface"
    name="pan_tilt" >

    <xacro:property name="base_link_length" value="0.05"  />
    <xacro:property name="base_link_radius" value="0.2"  />

    <xacro:property name="pan_link_length" value="0.5"  />
    <xacro:property name="pan_link_radius" value="0.02"  />

    <xacro:property name="bearing_radius" value="0.02"  />

    <xacro:property name="tilt_link_size" value="0.5 0.5 0.03"  />


    <xacro:macro name="inertial_matrix" params="mass">
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
        </inertial>
    </xacro:macro>

    <material name="yellow">
        <color rgba="1 1 0 1" />
    </material>
    <material name="blue">
        <color rgba="0 0 1 1" />
    </material>
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    <material name="green">
        <color rgba="1 0 0 1" />
    </material>
    
    <link name="base_link"><!-- It has  3 elements <visual>,<collision>,<inertial>-->
        <visual>
            <geometry>
                <cylinder length="${base_link_length}" radius="${base_link_radius}"/>
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0 " />
            <material name="yellow" />
        </visual>  
        <collision>
            <geometry>
                <cylinder length="${base_link_length+0.05}" radius="${base_link_radius+0.05}"/>
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0 " />
        </collision> 
        <!-- KDL does not support a root link with an inertia.  
            As a workaround, you can add an extra dummy link to your URDF. -->  
    </link>

    <link name="pan_link">
        <visual>
            <geometry>
                <cylinder length="${pan_link_length}" radius="${pan_link_radius}" />
            </geometry>
            <origin xyz="0 0 0.25" rpy="0 0 0 " />
            <material name="blue" />
        </visual>  
        <collision>
            <geometry>
                <cylinder length="${pan_link_length+0.05}" radius="${pan_link_radius+0.05}" />
            </geometry>
            <origin xyz="0 0 0.25" rpy="0 0 0 " />
        </collision>    
        <xacro:inertial_matrix mass="1" />       
    </link>

    <joint name="pan_joint"  type="revolute">
        <parent link="base_link" />
        <child link="pan_link" />
        <origin xyz="0 0 0.05" rpy="0 0 0 " />
        <axis xyz="0 0 1" /> <!-- Only rotate in Z-Axis -->

        <limit effort="300" velocity="1" lower="-3.14" upper="3.14" />
        <dynamics damping="50" friction="0.0" />
    </joint>

    <link name="bearing">
        <visual> 
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <sphere radius="${bearing_radius}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <sphere radius="${bearing_radius+0.05}" />
            </geometry>
        </collision>
        <xacro:inertial_matrix mass="1" />    
    </link>

    <joint name="bearing_joint" type="fixed">
        <parent link="pan_link" />
        <child link="bearing" />
        <origin xyz="0 0 0.5" rpy="0 0 0 " />
    </joint>

    <link name="tilt_link">
        <visual> 
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <box size="${tilt_link_size}" />
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <box size="0.55 0.55 0.035" />
            </geometry>
        </collision>
        <xacro:inertial_matrix mass="1" />    
    </link>

    <joint name="tilt_joint" type="revolute">
        <parent link="bearing" />
        <child link="tilt_link" />
        <origin xyz="0 0 0.035" rpy="0 0 0 " />

        <limit effort="300" velocity="1" lower="-1.3" upper="1.3" />
        <dynamics damping="5.0" friction="0.0" />
    </joint>

</robot>